- app/templates/server/app.js
feat(app): add mongodb error handling to quit app if unable to connect with mongodb server for some
reason
when the app will be started with grunt serve, if configured to run with mongodb and the service
will not be available, then the app will initialize anyway but mostly this isnt desired and no
handling or debug information of why the app has no connection to a mongodb server will be
provided
> feat(app): add mongodb error handling to quit app if unable to connect with

- app/templates/_package.json
Update grunt-build-control to v0.4.0
This PR is similar to PR #927 and would close #883 also.
> feat:app: grunt-build-control update to v0.4.0

- readme.md
MongoHQ has removed their free plan from Heroku. Adding MongoHQ with the current statement results in a monthly charge. MongoLab has a free sandbox plan and adding it is free.
> docs: changing from mongohq to mongolab

- app/templates/client/app/app(js).js
This PR adds event.preventDefault() to the $on('$stateChangeStart) Auth intercept because it fixed an intermittent bug in my code.
I made the following change in my code:
// Before:
if (next.authenticate && !loggedIn) {
$location.path('/login');
}
// After
if (!loggedIn && next.name !== 'login') {
event.preventDefault();
$state.go('login');
}
Before adding event.preventDefault(), the state intercept would intermittently fail to redirect the user to the login view. Specifically when clicking \<a href=""> links. Adding event.preventDefault() fixed the problem.
> fix(app): missing event.preventDefault

- .travis.yml
- app/index.js
- app/templates/Gruntfile.js
- app/templates/_package.json
- app/templates/client/index.html
- app/templates/karma.conf.js
- readme.md
- test/fixtures/bower.json
- test/fixtures/package.json
- test/test-file-creation.js
Add a follow up question to the first language selection question to enable
ES6 client support with Babel.
Closes #684
> feat(app): Add Babel option

- app/templates/e2e/account(auth)/login/login.spec(jasmine).js
- app/templates/e2e/account(auth)/login/login.spec(mocha).js
- app/templates/e2e/account(auth)/logout/logout.spec(jasmine).js
- app/templates/e2e/account(auth)/logout/logout.spec(mocha).js
- app/templates/e2e/account(auth)/signup/signup.spec(jasmine).js
- app/templates/e2e/account(auth)/signup/signup.spec(mocha).js
- app/templates/server/api/user(auth)/user.integration.js
- app/templates/server/api/user(auth)/user.model.spec(sequelizeModels).js
This fixes the `test:server` failures.
> fix(test): update sequelize destroy usage

- app/templates/server/api/user(auth)/user.model.spec(mongooseModels).js
- app/templates/server/api/user(auth)/user.model.spec(sequelizeModels).js
Both mongoose and sequelize user model implementations have
undesired effects when performing an update.
> test(model): refactor tests to expose model update bugs

- app/templates/_package.json
On default package.json, heroku deployment fails.
Just updating mongoose/connect-mongo package solves the issue for Heroku deployment.
> Update mongoose/connect-mongo to latest to deploy on Heroku

- .travis.yml
Testing on node `v0.11` isn't need now since `v0.12` is out.
> fix(travis): remove node v0.11 from testing

- app/templates/Gruntfile.js
Fix Grunfile.js ngAnnotate task src from `*/**.js` to `**/*.js`
> Fix Grunfile.js ngAnnotate task src

- readme.md
Changes:
- add documentation for `grunt test:coverage`
> docs(server-tests): update readme.md for new `test:coverage` task

- app/templates/client/app/account(auth)/login/login(html).html
- app/templates/client/app/account(auth)/login/login(jade).jade
- app/templates/client/app/account(auth)/settings/settings(html).html
- app/templates/client/app/account(auth)/settings/settings(jade).jade
- app/templates/client/app/account(auth)/signup/signup(html).html
- app/templates/client/app/account(auth)/signup/signup(jade).jade
- app/templates/client/app/admin(auth)/admin(html).html
- app/templates/client/app/admin(auth)/admin(jade).jade
- app/templates/client/app/main/main(html).html
- app/templates/client/app/main/main(jade).jade
- app/templates/client/components/navbar/navbar.directive(coffee).coffee
- app/templates/client/components/navbar/navbar.directive(js).js
- test/test-file-creation.js
> feat(app): implement navbar as directive

- app/templates/server/auth(auth)/facebook(facebookAuth)/passport.js
- app/templates/server/auth(auth)/google(googleAuth)/index.js
- app/templates/server/auth(auth)/google(googleAuth)/passport.js
There have been some API changes.
As of July 8th Facebook introduced v2.4 of their API. The default request only responds with id and name now.
If you create a Facebook app after July 8th you are forced to use v2.4 so this breaks the app (even though passport is currently defaulted to use v2.2, Facebook forces you).
Google has deprecated the use of `https://www.googleapis.com/auth/userinfo.profile` and `https://www.googleapis.com/auth/userinfo.email`. You should use `profile` and `email`.
> Update passport auth api

- app/templates/Gruntfile.js
- app/templates/_package.json
yeoman/grunt-filerev is a newer, more maintained module (than grunt-rev)
that provides file revisioning funtionality in a grunt task
> feat(build): switch to grunt-filerev

- package.json
- readme.md
> npm3 will no longer install peerDependencies, which is a very good change, but will impact how we currently use it
> chore(dependencies): remove `peerDependencies` and update docs to reflect

- readme.md
Heroku add-ons commands have changed. The old addons:add command is now deprecated. See here: https://devcenter.heroku.com/articles/managing-add-ons
> docs(gen): update readme.md to reflect new heroku commands

- app/templates/karma.conf.js
closes DaftMonk/generator-angular-fullstack#1081
> fix(app:test): include `client/components` in babel preprocessing

- app/templates/Gruntfile.js
> feat(grunt): add watch to bower.json

- app/templates/client/app/app(coffee).coffee
- app/templates/client/components/auth(auth)/auth.service(coffee).coffee
- app/templates/client/components/auth(auth)/auth.service(js).js
- app/templates/server/api/user(auth)/user.controller.js
in `app.js` there is an `event.preventDefault()` which wasn't present in the `coffee` version. I've added it.
https://github.com/DaftMonk/generator-angular-fullstack/blob/canary/app/templates/client/app/app(js).js#L52
the `auth.service#changePassword` method, shouldn't return anything on success, since the API is ending the request without any response as you can see.
https://github.com/DaftMonk/generator-angular-fullstack/blob/canary/app/templates/server/api/user(auth)/user.controller.js#L131
> app.coffee is missing preventDefault(); auth.service changePassword() chore

- app/templates/Gruntfile.js
98% of the time this does more harm than good. For those 2% you can just as easily run `grunt jade`.
> fix(grunt): `watch.jade` only watches jade files

- app/templates/_package.json
- package.json
Upgraded `grunt-contrib-jshint` to allow ES6 linting. It has jshint 2 as dependency. [More info](http://jshint.com/blog/2013-05-07/2-0-0/).
Also stylish being upgraded.
> feat(package): upgrade jshint packages

- app/templates/server/auth(auth)/auth.service.js
add role as second parameter, and attach to jwt
closes #382
> feat(server:auth): add role to signToken

- app/index.js
- script-base.js
Changes:
* `does()` now parses yeoman style escaped template: `<%%= name %>`
> feat(gen): test helper `does` accepts escaped template strings

- app/templates/Gruntfile.js
- app/templates/karma.conf.js
This matches the default jasmine spec timeout
> fix(app): increase mocha default timeout to 5000

- app/templates/_package.json
- app/templates/protractor.conf.js
- app/templates/server/api/user(auth)/user.model(mongooseModels).js
- app/templates/server/app.js
- app/templates/server/auth(auth)/auth.service.js
- app/templates/server/config/express.js
- endpoint/templates/basename.model(mongooseModels).js
Changes:
* Remove `mongoose-bird` dependency
* Add `bluebird` dependency
* Use `bluebird.promisifyAll` when requiring `mongoose` for models
* update mongoose to `^4.1.2`
> Feature: promisify mongoose directly

- app/templates/Gruntfile.js
- app/templates/_package.json
Changes:
* `grunt-contrib-watch` now uses `spawn: false` instead of `nospawn: true`
-- see: https://github.com/gruntjs/grunt-contrib-watch#optionsspawn
* `grunt-contrib-imagemin` now minifies svg files, remove `grunt-svgmin`
-- see: https://github.com/gruntjs/grunt-contrib-imagemin#imagemin-task
> Chore: update grunt deps

- app/index.js
- app/templates/client/app/main/main.controller.spec(coffee).coffee
- app/templates/client/app/main/main.controller.spec(js).js
- app/templates/client/components/auth(auth)/user.service(js).js
- app/templates/e2e/account(auth)/login/login.spec(mocha).js
- app/templates/e2e/account(auth)/logout/logout.spec(mocha).js
- app/templates/e2e/account(auth)/signup/signup.spec(mocha).js
- app/templates/e2e/main/main.spec(mocha).js
- app/templates/server/api/user(auth)/index.spec.js
- app/templates/server/api/user(auth)/user.integration.js
- app/templates/server/api/user(auth)/user.model.spec(mongooseModels).js
- app/templates/server/api/user(auth)/user.model.spec(sequelizeModels).js
- endpoint/templates/basename.integration.js
- endpoint/templates/index.spec.js
- script-base.js
Changes:
* Use `<%= expect() %>ASSERTION_SUBJECT<%= to() %>` syntax
* Implement dynamic assertions for all server tests including endpoints
* Default to `should` even when jasmine is chosen since there are no
jasmine server tests
* Refactor tests to comply with project indentation
closes DaftMonk/generator-angular-fullstack#1163
> feat(gen): replace `does` templating syntax

- app/templates/client/app/main/main.controller(coffee).coffee
- app/templates/client/app/main/main.controller(js).js
`success` and `error` promise have been deprecated.
resolves #1200
> refactor($http): change legacy promise to standard

- app/templates/client/app/account(auth)/login/login(html).html
- app/templates/client/app/account(auth)/login/login(jade).jade
- app/templates/e2e/account(auth)/login/login.spec(jasmine).js
- app/templates/e2e/account(auth)/login/login.spec(mocha).js
- app/templates/e2e/account(auth)/logout/logout.spec(jasmine).js
- app/templates/e2e/account(auth)/logout/logout.spec(mocha).js
- app/templates/e2e/account(auth)/signup/signup.spec(jasmine).js
- app/templates/e2e/account(auth)/signup/signup.spec(mocha).js
- app/templates/server/api/user(auth)/user.integration.js
- app/templates/server/api/user(auth)/user.model.spec(mongooseModels).js
- app/templates/server/api/user(auth)/user.model.spec(sequelizeModels).js
- app/templates/server/config/seed(models).js
Privately registered domain names such as admin.com should not
be used in seed or test data. Change the email address of the
'test' and 'admin' user accounts to 'test@example.com' and
'admin@example.com' respectively.
> refactor(data): Change seed user account emails to example.com

- heroku/index.js
chore (heroku): update heroku deployment generator angular-fullstack:heroku
Change instructions to use "heroku:create" instead of deprecated "heroku:add", and to use free "mongolab" instead of charged "mongohq" mongoseDB.
> update heroku deployment generator angular-fullstack:heroku

- app/generator.js
- endpoint/generator.js
- script-base.js
- util.js
also remove debugging `console.log`
> refactor(gen): remove legacy argument fix, and ES2015ify more

- .npmignore
This will reduce the published size quite a bit since `test/fixtures` was previously being published
[ci skip]
> feat(gen): ignore angular-fullstack-deps and test for npm publish

- app/USAGE
- app/generator.js
- readme.md
> fix(gen): expose `skip-install` option and improve usage docs

- app/generator.js
Requires DaftMonk/generator-ng-component#21
> fix(gen): force config update when it exists and `skipConfig == false`

- app/generator.js
- app/templates/_bower.json
- app/templates/client/app/account(auth)/settings/settings(html).html
- app/templates/client/app/account(auth)/settings/settings(jade).jade
- app/templates/client/app/account(auth)/signup/signup(html).html
- app/templates/client/app/account(auth)/signup/signup(jade).jade
- app/templates/e2e/account(auth)/signup/signup.po.js
- app/templates/e2e/account(auth)/signup/signup.spec(jasmine).js
- app/templates/e2e/account(auth)/signup/signup.spec(mocha).js
Originally submitted by @thomporter
Closes #484
> feat(auth): add confirm password to signup and settings

- CHANGELOG.md
- Gruntfile.js
- package.json
- task-utils/changelog-templates/commit.hbs
- task-utils/grunt.js
Also regenerated `2.x.x` releases with new `conventional-changelog`.
> chore(gen): update grunt-conventional-changelog to `^4.1.0`

- app/templates/client/app/main/main(html).html
- app/templates/client/app/main/main(jade).jade
- app/templates/client/app/main/main(js).js
- app/templates/client/app/main/main.controller(js).js
- app/templates/client/app/main/main.controller.spec(js).js
controller as main, MainCtrl -> MainController
> refactor(client:main): use controller as, named function, new name

- app/generator.js
- app/templates/Gruntfile.js
- app/templates/client/app/admin(auth)/admin(js).js
- app/templates/client/app/app(js).js
- app/templates/client/app/main/main.controller(js).js
- app/templates/client/components/auth(auth)/auth.module(js).js
- app/templates/client/components/auth(auth)/auth.service(js).js
- app/templates/client/components/auth(auth)/interceptor.service(js).js
- app/templates/client/components/auth(auth)/router.decorator(js).js
- app/templates/client/components/auth(auth)/user.service(js).js
- app/templates/client/components/util/util.module.js
- app/templates/client/components/util/util.service.js
- test/test-file-creation.js
Changes:
* `injector:scripts` sorts `*.module.js` first 
* create auth module
* move all auth related config and functionality to auth module
* use named functions
* implement route authentication via router.decorator
* add `Auth.hasRole`
* implement `Util` service
* restrict `Authorization` header to same origin
> Feature: auth module

- app/templates/_package.json
Changes:
* require `chai`, `sinon`, and `phantomjs` directly
> chore(dependencies): require peer-dependant modules directly, per npm 3+

- .travis.yml
- app/templates/.travis.yml
We'll allow failures on node 4.0.0 for now. If we start seeing node 4.0.0 passing in travis, we can remove the `allow_failures`.
> chore(travis): add node 4.0.0 to travis targets

- app/templates/_package.json
Update grunt-contrib-imagemin version to fix the error when using npm
install with Node v4.2.2
Closes #1412
> chore(npm): grunt-contrib-imagemin ^0.9.4 -> 1.0.0

- app/templates/Gruntfile.js
- app/templates/client/.jshintrc
- app/templates/client/app/account(auth)/account.js
- app/templates/client/app/account(auth)/login/login(html).html
- app/templates/client/app/account(auth)/login/login(jade).jade
- app/templates/client/app/account(auth)/login/login.controller.js
- app/templates/client/app/account(auth)/settings/settings(html).html
- app/templates/client/app/account(auth)/settings/settings(jade).jade
- app/templates/client/app/account(auth)/settings/settings.controller.js
- app/templates/client/app/account(auth)/signup/signup(html).html
- app/templates/client/app/account(auth)/signup/signup(jade).jade
- app/templates/client/app/account(auth)/signup/signup.controller.js
- app/templates/client/components/navbar/navbar(html).html
- app/templates/client/components/navbar/navbar(jade).jade
- app/templates/client/components/navbar/navbar.controller.js
- app/templates/client/components/navbar/navbar.directive.js
- app/templates/e2e/account(auth)/login/login.po.js
- app/templates/e2e/account(auth)/signup/signup.po.js
- app/templates/karma.conf.js
> More controller as

- app/templates/gulpfile.babel(gulp).js
without `es7.classProperties`, babel won't compile the default controller template
> fix(gulp): add babel runtime options

- app/templates/e2e/account(auth)/login/login.spec(jasmine).js
- app/templates/e2e/account(auth)/logout/logout.spec(jasmine).js
- app/templates/e2e/account(auth)/signup/signup.spec(jasmine).js
jasmine e2e tests will occasionally fail with a "failed to sync" error
declaring `window.angular is undefined.`. Update e2e tests to force them
to wait for angular to be declared.
> fix(e2e): force e2e tests to wait for angular

- app/templates/server/api/user(auth)/user.integration.js
- app/templates/server/api/user(auth)/user.model.spec(mongooseModels).js
- app/templates/server/app.js
- endpoint/templates/basename.integration.js
mocha unit and integration tests will hang unless express (and
optionally mongoose) are closed once the tests are complete
> fix(mocha): have tests clean up once complete

- app/templates/_package.json
- app/templates/gulpfile.babel(gulp).js
Over the last week and a bit I've been testing and updating the gulp file (and some tests) aiming for parity with grunt.  I've merged all my changes, piece by piece, into the generator and tested the results.
More testing will be required, but hopefully this will help bring gulp support closer to release.
> feat(gulp): grunt parity

- app/templates/client/components/util/util.service.js
`isSameOrigin` always returns `false` in IE, thus user is never able to login.
> IE doesn't populate all link properties when setting .href with a relative URL,
> however .href will return an absolute URL which then can be used on itself
> to populate these additional fields.
Thanks to http://stackoverflow.com/a/13405933
> fix(client:util.urlParse): special treatment for IE

- app/templates/server/api/user(auth)/user.controller.js
- endpoint/templates/basename.controller.js
use import statements and remove/rename promise helpers
> Refactor api controller

- app/templates/gulpfile.babel(gulp).js
- app/templates/mocha.global(gulp).js
- app/templates/server/app.js
mocha unit and integration tests will hang unless express (and
optionally mongoose) are closed once the tests are complete
> fix(gulp:mocha): have tests clean up once complete

- app/templates/_.gitignore
- app/templates/_package.json
- app/templates/gulpfile.babel(gulp).js
> fix(gulp): make coverage tests work

- app/templates/server/api/user(auth)/user.controller.js
- app/templates/server/api/user(auth)/user.model(mongooseModels).js
- app/templates/server/api/user(auth)/user.model(sequelizeModels).js
- app/templates/server/api/user(auth)/user.model.spec(mongooseModels).js
- app/templates/server/api/user(auth)/user.model.spec(sequelizeModels).js
- app/templates/server/auth(auth)/local/passport.js
based on PR #1049 from @Awk34 commit (5fecaba).
Hi, this is another attempt at excluding the password info by default and not just at query time. The sequelize way of doing it is not pretty but seems to be the [recommended](https://github.com/sequelize/sequelize/issues/1462#issuecomment-168383832) way. And it does not look like there will be a different way anytime soon.
> refactor(model:user): exclude password info by default

- app/generator.js
This won't do anything until we release a new version of generator-ng-component and bump the version required here
> feat(gen): add 'es6' to generator-ng-component filters

- readme.md
The route generator asks for a module name. Add it to match the usage experience.
I read that I should push fixes to canary, but that doesn't apply to a docfix for the current version, does it?
> docs(readme): add module name question to route generator example

- app/templates/gulpfile.babel(gulp).js
- app/templates/server/api/user(auth)/user.model(mongooseModels).js
- app/templates/server/api/user(auth)/user.model.spec(mongooseModels).js
If no email and password were passed to the authentication endpoints,
the authentication would still succeed even though there was no email
and password. This fixes that to make sure that we account for blank and
null email and passwords. Also it makes sure that email
and password are not required when using other oauth providers.
> fix(user): fix email and password validation

- app/templates/server/config/express.js
> fix(livereload): ignore api routes and specific non-html files

- app/templates/gulpfile.babel(gulp).js
When running `gulp build` the rev manifest will be remade, but the task
"build:client" which uses this file doesn't depend on "build:images"
which populates this file. The result is that when running `build`,
rev-replace will be unable to replace images as it doesn't wait for
images to be filled in.
Solution is to simply have "build:client" depend upon "build:images"
> fix(gulp): build images before rev-replace

- app/templates/gulpfile.babel(gulp).js
Fixes two bugs leading to gulp + typescript builds to not launch tests properly.
Closes issue #1748
> fix(ts): fix typo of gulp's typescript test configuration file

- app/templates/gulpfile.babel(gulp).js
Closes two issues: #1830 and #1828.
The fix for issue #1830 is pretty straight-forward and think the extra task and refactoring of the old task to an external function for issue #1828 are relatively small as well. 
I am however a bit concerned that the refactoring might not necessarily comply with the preferred coding style for the repository. Should the function rather be a separate task? Or be moved into helper functions above?
Either way, I figure that the `injectTsConfig` function could be used for a future `tsconfig.server.json` and `tsconfig.server.test.json`. So think it's at least better than copy + paste.
> gulp:ts: fix ts copy of constant file and inject test client .ts files automatically.

- templates/app/server/config/express.js
Fixes an upstream issue in express-session or express-sequelize-session
where static middleware requests:
- Hit the session store,
- Overwrite one another, and
- Generate many new sessions.
Fixes #1668.
> (fix:express): reorder static middleware

- templates/app/gulpfile.babel(gulp).js
Change execution order for gulp tasks 'transpile:client' and 'html' to fix the templateCache generation.
closes #1936
> fix(build): fix templateCache generation on gulpfile (#1936)

- templates/app/gulpfile.babel(gulp).js
- templates/app/tsconfig.client(ts).json
- templates/app/tsconfig.client.test(ts).json
So far, two small fixes to get `gulp build` up and running again. Could perhaps do the rest of the gulp clean up mentioned in #1196 here.
Removed tsconfig injection and files in tsconfig's as webpack does not use it.
> Webpack gulp clean up

- templates/app/_package.json
- templates/app/gulpfile.babel.js
- templates/app/server/config/environment/index.js
- templates/app/server/config/express.js
Closes #1955.
As the title says, this commit replaces the `livereload` functionality with browser-sync. The greatest benefit this gives is the possibility to get multiple windows on multiple devices to update for each change. Additionally granting scroll, click and form input mirroring. Thus essentially enabling the testing of multiple devices at a time.
The only controversial change I can think of is likely the switch to a separate port when in development while the earlier default port is used to proxy both static content and the API.
That new port is hard-coded in the config file (next to the `devPort`) to the browser-sync default of 3000.  Figure two changes could me made:
1. Add some kind of customization similar to `devPort` to the browser-sync-port
2. Change the browser-sync port …
> feat(project): replace livereload with browser-sync

- package.json
- src/generators/app/index.js
- src/generators/component/index.js
- src/generators/controller/index.js
- src/generators/decorator/index.js
- src/generators/directive/index.js
- src/generators/filter/index.js
- src/generators/provider/index.js
- src/generators/route/index.js
- src/generators/service/index.js
- src/test/fixtures/.yo-rc.json
- src/test/main.test.js
> generator-ng-component 1.0.0

- templates/app/gulpfile.babel.js
Pushing towards master since easy but seemingly critical fixes and canary seems a bit outdated.
> Typings build

- templates/app/server/config/express.js
move strip-ansi & browsersync to dev-only section
> fix(server): fix dev-only imports

- templates/app/_package.json
- templates/app/gulpfile.babel.js
> chore(package): remove old unused deps

- templates/app/_package.json
> fix(webpack): fix peerDependencies for css loaders

- package.json
- src/generators/app/index.js
- templates/app/.eslintrc
- templates/app/client/app/account(auth)/login/index.js
- templates/app/client/app/account(auth)/settings/index.js
- templates/app/client/app/account(auth)/signup/index.js
- templates/app/client/app/account(auth)/signup/signup.controller.js
- templates/app/client/app/admin(auth)/index.js
- templates/app/client/app/app.js
- templates/app/client/components/auth(auth)/auth.service.js
- templates/app/client/components/auth(auth)/router.decorator.js
- templates/app/client/components/modal(uibootstrap)/modal.service.js
- templates/app/client/components/mongoose-error(auth)/mongoose-error.directive.js
- templates/app/client/components/navbar/navbar.component.js
- templates/app/client/components/oauth-buttons(oauth)/index.js
- templates/app/client/components/socket(socketio)/socket.service.js
- templates/app/client/components/util/util.module.js
- templates/app/client/components/util/util.service.js
- templates/app/server/api/user(auth)/user.controller.js
- templates/app/server/api/user(auth)/user.events.js
- templates/app/server/api/user(auth)/user.model(mongooseModels).js
- templates/app/server/app.js
- templates/app/server/auth(auth)/auth.service.js
- templates/app/server/auth(auth)/index.js
- templates/app/server/config/express.js
- templates/app/server/config/seed(models).js
- templates/app/server/config/socketio(socketio).js
with `fix` enabled. Should automatically get rid of a lot of ESLint issues.
fixes #2157
> Fix ESLint errors

- templates/app/webpack.make.js
exclude angular-socket-io when user doesn't select socket.io
fixes #2172
> fix(webpack): fix webpack vendor import

- templates/app/client/components/auth(auth)/auth.service.js
> fix(client:auth): fix hasOwnProperty instances, fix User usage

- readme.md
- [give me a break] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
The node-gyp prerequisite was not making it clear that it is related to the npm install part of the Usage guide.
> docs(readme): Add a more explicit advice for compiling native add-ons

- package.json
- src/generators/app/index.js
- templates/app/client/app/account(auth)/account.module.js
- templates/app/client/app/account(auth)/login/login.component.js
- templates/app/client/app/account(auth)/settings/settings.component.js
- templates/app/client/app/account(auth)/signup/signup.component.js
- templates/app/client/app/app.component.js
- templates/app/client/app/app.constants.js
- templates/app/client/app/app.module.js
- templates/app/client/app/main/main.component.js
- templates/app/client/app/main/main.module.js
- templates/app/client/components/auth(auth)/auth.module.js
- templates/app/client/components/auth(auth)/auth.service.js
- templates/app/client/components/auth(auth)/user.service.js
- templates/app/client/components/directives.module.js
- templates/app/client/components/footer/footer.component.js
- templates/app/client/components/navbar/navbar.component.js
- templates/app/client/components/oauth-buttons(oauth)/oauth-buttons.component.js
- templates/app/client/components/socket(socketio)/socket.service.js
- templates/app/server/config/environment/shared.js
this is a proper codemod tool, instead of a general transpiler like babel
> feat(gen): generate js with jscodeshift instead of babel

- templates/app/webpack.make.js
> fix(webpack:css): disable css-loader sourceMap option

- docs/Examples/IIS.md
There is no reason to run ```gulp serve:dist``` after you build the first time. This will clear your web.config from your `client` folder.
> Updated IIS.md

- templates/app/server/app.js
- templates/app/server/config/seed(models).js
Previously, .sync() was being called once in server/config/seed.js and once during sqldb.sequelize.sync() in server/app.js. As a result, duplicate queries were being sent to the database if the tables needed to be defined causing an error when it tries to define constraints a second time (like for an identity column).
Seed.js is wrapped in a function and contains the conditional to determine whether to seed the database. This makes it easy to include in the promise chain under sqldb.sequelize.sync().
> fix (app): prevent excess sync() calls during db seed

- templates/app/server/api/user(auth)/user.events.js
- templates/app/server/api/user(auth)/user.model(mongooseModels).js
- templates/endpoint/basename.events(models).js
- templates/endpoint/basename.model(mongooseModels).js
As of `mongoose@4.8.0` schema events should be registered before the model is compiled
fixes #2479
> fix(events): mongoose event registration

- templates/app/_package.json
- templates/app/gulpfile.babel.js
> chore(package): remove gulp-node-inspector

- templates/app/_bower.json
- templates/app/client/index.html
- templates/app/gulpfile.babel(gulp).js
Fix 
Remove socket.io-client from index.html
Add socket-io-client to bower.json
Fix issue with gulpfile wiredep:client removing the string 'client' from any added packages with the word 'client' in it's name
Closes issue #2524
> Fix for issue #2524

- templates/app/.eslintrc
- templates/app/client/app/app.js
- templates/app/client/components/auth(auth)/auth.service.js
- templates/app/client/components/modal(uibootstrap)/modal.service.js
- templates/app/server/api/user(auth)/user.model(mongooseModels).js
- templates/app/server/api/user(auth)/user.model(sequelizeModels).js
- templates/app/server/config/seed(models).js
- templates/endpoint/basename.controller.js
This PR fixes all warnings and linter errors plus deprecated warnings with the default configuration when installing via yo.
Before:
```bash
~/d/test $ gulp serve                                                                                                                          13:51:15
[13:53:48] Requiring external module babel-register
[13:53:50] Using gulpfile ~/dev/test/gulpfile.babel.js
[13:53:50] Starting 'serve'...
[13:53:50] Starting 'clean:tmp'...
[13:53:50] Starting 'lint:scripts'...
[13:53:50] Starting 'lint:scripts:client'...
[13:53:50] Starting 'lint:scripts:server'...
[13:53:50] Starting 'inject'...
[13:53:50] Starting 'inject:scss'...
[13:53:50] Starting 'copy:fonts:dev'...
[13:53:50] Starting 'env:all'...
[13:53:50] Finished 'env:all' after 8.36 ms
[13:53:50] Finished …
```
> Resolve all Warnings and Deprecated Messages with Default Configuration.

- gulpfile.js
- src/generators/app/index.js
checks if yarn is available and runs yarn install on setup. falls back to npm if yarn is not
installed.
> Adds Support for Yarn Install If Supported

- templates/app/tsconfig(ts).json
- templates/app/tsconfig.client.test(ts).json
fix module resolution for typescript when module are located in folder node_modules.
> fix(tsconfig): fix module resolution for typescript

- templates/app/tsconfig(ts).json
- [x ] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [x ] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
Move setting moduleResolution inside compilerOptions section to allow module resolution to work as expected.
> fix(tsconfig) Move setting moduleResolution inside compilerOptions section

- templates/app/client/components/auth(auth)/auth.service.js
> fix(client:auth): fix isAdmin call

- templates/app/tsconfig(ts).json
- [ x] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [ x] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
> fix(ts): exclude typescript spec files generating errors on transpilling

- templates/app/webpack.make.js
Fixed two comma typos in webpack.make.js which caused problems when calling `npm run start:client` on some node/npm versions
> fix(app): fix webpack.make.js typos

- templates/app/_package.json
Changed required node version to >= 6.x.x for now (like discussed in #2696), so that the installation is not limited to node 6.
Also npm >= 3.9.5, since current version is 5.7.1.
I am using rc1 with node 8.10.0 + npm 5.7.1 and haven't encountered any issues so far.
Closes #2696
> fix(app): wrong engines in package.json #2696

- templates/app/server/config/express.js
- [] The generator's tests pass (`generator-angular-fullstack$ npm test`) 
- But they didn't run beforehand... however npm run start:server now works.
Hi! This pull will fix Issue #2732 and make the session store work for those using sequelize.
> Issue #2732: SequelizeStore needs to be created object containing db reference

- docs/content/deployment/gcloud-deployment.md
- docs/content/deployment/index.md
- [ x] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [ x] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
- [ x] The generator's tests pass (`generator-angular-fullstack$ npm test`)
Instructions to deploy on Google Cloud App Engine's Standard environment
> docs(deployment): instructions to deploy on gcloud app engine standard edition

- templates/app/_package.json
- templates/app/server/api/user(auth)/user.model(sequelizeModels).js
- templates/app/server/config/environment/development.js
- templates/app/server/config/environment/production.js
- templates/app/server/config/environment/test.js
Update sequelize to v4 and fix the user model to work with this.
Part of #2691
> chore(server): Update to sequelize 4

- src/generators/app/index.js
- templates/app/server/api/user(auth)/user.model(mongooseModels).js
- templates/app/server/api/user(auth)/user.model(sequelizeModels).js
new Buffer(...) has been deprecated since node v6.0.0 and Buffer.from methods should used instead
Fixes #2753
(This pull request will conflict with pull request #2750 -  but the conflict is very easy to resolve.)
> chore(server): migrate from new Buffer to Buffer.from

- package.json
- src/test/main.test.js
- templates/app/_package.json
- templates/app/client/components/util.js
- templates/app/gulpfile.babel.js
> chore(app): update several components

- templates/app/webpack.make.js
Since the file is also imported, this caused Zone.js to be loaded twice, which was breaking the front end
fixes #2764
> fix(client): remove polyfills from Webpack entry

- templates/app/gulpfile.babel.js
/client/.htaccess is no longer part of the project
> fix(gulpfile): removed ref to .htaccess
