angular-fullstack/generator-angular-fullstack

- app/templates/server/config/environment/index.js
adding support for a default configuration parameter for all environments to specify IP address, just like there's a port configuration by default (```production.js``` env configuration file already references this config parameter)
> Config parameter for ip address information

- app/templates/_package.json
update jwt packages due to security vulnerabilities
> chore(package.json): update jwt versions

- app/templates/client/app/admin(auth)/admin.controller(coffee).coffee
- app/templates/client/app/admin(auth)/admin.controller(js).js
no need of iteration for removing the user from the list, just use angular index ng-repeat property
> chore(admin): splice user without iteration

- app/templates/client/app/main/main(css).css
- app/templates/client/app/main/main(less).less
- app/templates/client/app/main/main(sass).scss
- app/templates/client/app/main/main(stylus).styl
> fix css bug

- app/templates/_package.json
Proposed changes by Daftmonk was implemented in prior versions
would close also #883
> feat:app: grunt-build-control to v0.4.0

- app/templates/client/components/modal(uibootstrap)/modal.service(js).js
Fixed missing "r" in word "straight" in comment.
> Fixed typo in Modal service comments.

- app/templates/server/api/user(auth)/user.model(mongooseModels).js
- app/templates/server/api/user(auth)/user.model(sequelizeModels).js
- app/templates/server/api/user(auth)/user.model.spec(mongooseModels).js
- app/templates/server/api/user(auth)/user.model.spec(sequelizeModels).js
> fix(model): fix update bugs with mongoose and sequelize

- app/templates/_package.json
> chore(dependencies): update connect-livereload

- app/templates/Gruntfile.js
> fix(build): exclued `bower_components` from the rev and usemin blocks

- app/templates/Gruntfile.js
fix(gen:build): Adds missing slash
Adds missing slash
> fix(gen:build): Adds missing slash

- app/templates/server/config/environment/index.js
closes DaftMonk/generator-angular-fullstack#1071
> fix(app): use 0.0.0.0 for default IP

- app/templates/Gruntfile.js
- app/templates/_package.json
grunt-autoprefixer is dead, long live grunt-postcss.
Now with less diff!
> Feat(grunt): remove grunt-autoprefixer, add grunt-postcss

- app/templates/client/components/auth(auth)/auth.service(js).js
$cookieStore is deprecated. See https://docs.angularjs.org/api/ngCookies/service/$cookieStore
> refactor(client:auth): use $cookies instead

- app/index.js
This takes care of the README.md template as well as allowing
other template updates related to the grunt/gulp implementation
> fix(gen): default grunt filter

- app/templates/client/components/auth(auth)/auth.service(coffee).coffee
- app/templates/client/components/auth(auth)/auth.service(js).js
> fix(app): auth.login waits for user resource to resolve

- app/templates/Gruntfile.js
- app/templates/_package.json
- app/templates/karma.conf.js
> feat(app): use wiredep to inject bower deps into karma.conf.js

- app/templates/server/components/errors/index.js
> fix(server:errors): fix res.render syntax

- app/templates/Gruntfile.js
- app/templates/client/app/app(less).less
- app/templates/client/app/app(sass).scss
- app/templates/client/app/app(stylus).styl
> fix(gen:css): ensure scss/less/stylus files have proper relative paths

- app/templates/Gruntfile.js
- app/templates/_bower.json
- readme.md
> remove angular-scenario module

- app/templates/_package.json
- app/templates/server/config/socketio(socketio).js
Changes:
* Update socket.io and related deps
* Update socketio-jwt doc comment
* Update `socket.address` reference
> Fix: update socketio & doc info

- app/templates/client/app/admin(auth)/admin.controller(coffee).coffee
> refactor(admin:controller): use User.query

- app/templates/Gruntfile.js
> fix(app): include `client/*.html` in usemin html glob

- app/templates/server/auth(auth)/auth.service.js
> fix(auth): setTokenCookie sets token as string

- util.js
> fix(gen): templateIsUsable uses self.filters by default

- app/index.js
- endpoint/index.js
> fix(gen): allow generator to be transpiled as a node_module

- app/templates/_package.json
> fix(npm): always include grunt-babel

- readme.md
> docs(README): add note about `grunt serve:debug`

- app/templates/client/app/main/main.controller.js
> Main controller as class

- app/templates/server/config/environment/development.js
- app/templates/server/config/environment/production.js
> fix(server:config): template db configs and add sequelize prod conf

- app/templates/gulpfile.babel(gulp).js
Hi
These two commits fixes some minor issues that caused gulp to crash during execution
> (gulp) Minor fixes

- app/templates/gulpfile.babel(gulp).js
update `test:client` dependencies and ensure correct async run hints
> fix(gulp:test): fix gulp test dependencies

- app/templates/client/app/account(auth)/login/login(html).html
- app/templates/client/app/account(auth)/login/login(jade).jade
- app/templates/client/app/account(auth)/settings/settings(html).html
- app/templates/client/app/account(auth)/settings/settings(jade).jade
- app/templates/client/app/account(auth)/signup/signup(html).html
- app/templates/client/app/account(auth)/signup/signup(jade).jade
- app/templates/client/app/admin(auth)/admin(html).html
- app/templates/client/app/admin(auth)/admin(jade).jade
- app/templates/client/app/main/main(html).html
- app/templates/client/app/main/main(jade).jade
- app/templates/client/index.html
move navbar and footer directive usage to around the router view directive in index.html
> feat(client): move navbar and footer directive 

- readme.md
shields.io provides consistent and stylable badges for opensource projects
> refactor(readme): use consistent badges

- app/templates/server/config/environment/development.js
> docs(app):fix typo

- app/templates/gulpfile.babel(gulp).js
> fix(gulp:watch): re-compile jade to .tmp

- app/templates/_bower.json
- app/templates/client/app/main/main(html).html
- app/templates/client/app/main/main(jade).jade
- app/templates/client/components/modal(uibootstrap)/modal.service.js
- app/templates/client/components/navbar/navbar(html).html
- app/templates/client/components/navbar/navbar(jade).jade
> chore(bower): upgrade angular-bootstrap to ~1.1.2

- app/templates/_bower.json
- app/templates/_package.json
- app/templates/client/app/main/main(html).html
- app/templates/client/app/main/main(jade).jade
- app/templates/client/app/main/main.controller.js
- app/templates/client/app/main/main.controller.spec.js
- app/templates/client/app/main/main.js
> Angular 1.5

- app/templates/gulpfile.babel(gulp).js
> fix(gulp:serve): add `env:all`

- app/templates/_package.json
- app/templates/gulpfile.babel(gulp).js
> feat(gulp): port `grunt buildcontrol` tasks over to gulp

- templates/app/Gruntfile(grunt).js
> feat(grunt:less): add sourcemap options

- src/generators/generator-base.js
show raw stdout if yo >= 1.7.1 check fails
> feat(genBase): show raw stdout for yo check

- docs/index.md
>  docs(project structure): fix typo

- templates/app/_package.json
> chore(package): update gulp-angular-templatecache to 2.0.0

- templates/app/gulpfile.babel(gulp).js
> fix(gulp): fix plain css generation

- templates/app/_package.json
> chore(package): pin sequelize to a higher version

- templates/app/_package.json
- templates/app/server/config/express.js
> chore(server): replace compression with shrink-ray

- templates/app/_package.json
Update required engine versions in the generated `package.json` to make it same as in the generator's `package.json`.
> chore(package): update node/npm versions in the generated package.json

- templates/app/_package.json
> chore(package): set istanbul to 1.1.0-alpha.1

- templates/app/_package.json
this shouldn't really affect the generated project
> chore(package): bump ui-bootstrap to v2

- templates/app/_package.json
> chore(package): update bootstrap-social to ^5.0.0

- templates/app/_package.json
> chore(package): bump ui-router to ~0.3.1

- templates/app/_package.json
> chore(package): bump flow-bin to 0.30

- templates/app/client/components/oauth-buttons(oauth)/index.js
> fix(client:oauthButtons): add ngInject

- templates/app/client/components/socket(socketio)/socket.service.js
> fix(socket): add ngInject

- docs/generators/app.md
- docs/generators/component.md
- docs/generators/controller.md
- docs/generators/decorator.md
- docs/generators/directive.md
- docs/generators/endpoint.md
- docs/generators/filter.md
- docs/generators/route.md
- docs/generators/service.md
add missing lines (e.g. module name question)
> docs(generators): update docs

- templates/app/_package.json
https://snyk.io/vuln/npm%3Aejs%3A20161128
> chore(package): bump ejs to ^2.5.3

- templates/app/_package.json
> chore(package): upgrade to Angular 1.6

- circle.yml
> ci(circle): change build order to cache deps

- templates/app/client/app/account(auth)/signup/signup.controller.js
> Fix form field not displaying sequalize error

- templates/app/server/api/user(auth)/index.spec.js
- templates/app/server/api/user(auth)/user.integration.js
- templates/endpoint/basename.integration.js
- templates/endpoint/index.spec.js
> fix(eslint): hides global variable warnings

- templates/app/_package.json
> chore(package): update awesome typescript loader

- templates/app/_package.json
> chore(package): bump morgan

- templates/app/client/app/account(auth)/account.module.js
- [x ] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [x ] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
fix oauth webpack issue into account module
fix webpack issue related to oauth selection filter into the account module
> fix(account module): fix oauth webpack issue into account module

- circle.yml
> CircleCI 2

- package.json
- src/generators/app/index.js
- src/generators/endpoint/index.js
- src/generators/generator-base.js
> chore(gen): update yeoman-generator to 1.x

- templates/app/_package.json
- templates/app/server/config/express.js
> Replace express-sequelize-session with connect-session-sequelize

- templates/app/server/api/user(auth)/user.model(mongooseModels).js
- templates/app/server/api/user(auth)/user.model(sequelizeModels).js
> fix(server:auth): specify digest for pbkdf2

- templates/app/client/components/directives.module.js
- templates/app/client/components/navbar/navbar.html
> fix(ui-bootstrap): fixing errors when using bootstrap without ui-bootstrap

- templates/app/_package.json
- templates/app/server/config/express.js
> chore(server): switch back from shrink-ray to compression

- templates/app/_package.json
> chore(package): lock Typescript to 2.5.2

- templates/app/_package.json
- templates/app/webpack.make.js
> feat(package): add start scripts

- templates/app/webpack.server.js
Fixed server.start() parameters to correct function signature.
closes issue #2697
> fix(app): fix webpack dev server issue #2697

- templates/app/_package.json
This update is required to allow the generator to work with node v10.0.0
Part of #2691
> chore(package): Update node-sqlite3 dependency

- src/generators/app/index.js
- templates/app/client/app/account(auth)/settings/settings.html
This patch fixes the issue #2747
> fix(auth): fix change password form

- templates/app/server/app.js
Fixes #2751
- [?] The generator's tests pass (`generator-angular-fullstack$ npm test`)
> fix(server): wsInitPromise should be passed into then in a function

- package.json
> chore(package): bump lodash

- templates/app/client/app/polyfills.js
> fix(polyfills): manually import `reflect-metadata`
